//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTW.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Đăng ký")]
        public string MAIL_REGISTER_SUBJECT {
            get {
                return ((string)(this["MAIL_REGISTER_SUBJECT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xin chào {0}! Chúc mừng bạn đã đăng ký thành công")]
        public string MAIL_REGISTER_BODY {
            get {
                return ((string)(this["MAIL_REGISTER_BODY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4thangngocabc@gmail.com")]
        public string MAIL_FROM {
            get {
                return ((string)(this["MAIL_FROM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12322321")]
        public string MAIL_PASSWORD {
            get {
                return ((string)(this["MAIL_PASSWORD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xin chào {0}! Chúc mừng bạn đã đặt hàng thành công")]
        public string MAIL_ORDER_BODY {
            get {
                return ((string)(this["MAIL_ORDER_BODY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xin chào {0}! Mật khẩu của bạn đã được reset , mật khẩu của bạn là :123456 . Vui " +
            "lòng không được tiết lộ")]
        public string MAIL_TAIKHOAN_BODY {
            get {
                return ((string)(this["MAIL_TAIKHOAN_BODY"]));
            }
        }
    }
}
